# Generated by Django 3.2 on 2022-06-01 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("checkout", "0002_order_order_total"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="delivery_cost",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=6
            ),
        ),
    ]
